from turtle import Turtle,Screen
dark=Turtle()
screen=Screen()
dark.color("red")
dark.pensize(20)
dark.speed(1)
dark.hideturtle()
dark.left(45)
dark.forward(200)
dark.circle(100,180)
dark.right(90)
dark.circle(100,180)
dark.home()
screen.exitonclick()