import turtle
window = turtle.Screen()
window.bgcolor("black")
border_turtle = turtle.Turtle()
border_turtle.speed(3)
border_turtle.color("silver")
border_turtle.pensize(3)
def draw_border():
    border_turtle.penup()
    border_turtle.goto(-350, -350)
    border_turtle.pendown()
    for _ in range(4):
        border_turtle.forward(700)
        border_turtle.left(90)
draw_border()
window = turtle.Screen()
window.bgcolor("black")
invitation_turtle = turtle.Turtle()
invitation_turtle.speed(1)
invitation_turtle.color("orange")
invitation_turtle.penup()
invitation_turtle.goto(0, 100)
invitation_turtle.write("🎀Wedding💞Invitation🎀", align="center", font=("Arial", 30, "bold"))
invitation_turtle.goto(0, 40)
invitation_turtle.color("silver")
invitation_turtle.write("name 1", align="center", font=("Courier", 20, "normal"))
invitation_turtle.goto(0, -20)
invitation_turtle.color("deep pink")
invitation_turtle.write("💘WEDS", align="center", font=("Arial", 30, "normal"))
invitation_turtle.goto(0, -60)
invitation_turtle.color("silver")
invitation_turtle.write("name 2", align="center", font=("Courier", 20, "normal"))
invitation_turtle.goto(0, -160)
invitation_turtle.color("midnight blue")
invitation_turtle.write("Date:", align="center", font=("Arial", 20, "normal"))
invitation_turtle.goto(0, -200)
invitation_turtle.write("Location:", align="center", font=("Arial", 20, "normal"))
window.exitonclick()
